### ISSUE TITLE
release the source code

### ISSUE THREAD

**Issue by hxy-62** [starsuzi/Adaptive-RAG#1]

**Comment by LeoX91** [comment]
Any news about the source and the classifier?

**Comment by mhood-rcp** [comment]
UNEXPECTED CYCLE in GRAPH: Paper contains a link to the source code which only contains a link to the paper.

**Comment by starsuzi** [comment]
Thanks for having an interest in our work! We will release the code soon, so stay tuned!

**Comment by starsuzi** [comment]
We released the code! Thank you.
