### ISSUE TITLE
Token indices sequence length is longer than the specified maximum sequence length for this model (522 > 512). Running this sequence through the model will result in indexing errors

### ISSUE THREAD

**Issue by hxy-62** [starsuzi/Adaptive-RAG#3]
when I running the code: bash run_retrieval_dev.sh &SYSTEM $MODEL $DATASET $LLM_PORT_NUM, error occur: Token indices sequence length is longer than the specified maximum sequence length for this model (522 > 512). Running this sequence through the model will result in indexing errors.

**Comment by starsuzi** [comment]
I think it is a warning rather than an error; so you can just go ahead. :)
